# Group Aweber


## Aweber List [/aweber/]

### Aweber Contact List[GET]

Aweber API helps you check all your contact list in Aweber. Aweber is an email marketing tool.
+ Response 200 (application/json)
    + Body
    
            {

            }


### Update A Aweber Contact [POST]
This API endpoint allows you edit and update you Aweber contact
+ Request (application/json)
    + Body
    
            {

            }

+ Response 201 (application/json)
    + Body
    
            {

            }