# Group campaignmonitor


## CampaignMonitor List [/campaignmonitor/]

### CampaignMonitor Contact List[GET]
This API lets you check CampaignMonitor contact list. It's one of the best email marketing and automation tool

Fetches Campaignmonitor List

+ Response 200 (application/json)
    + Body
    
            {
                "success":true,
                "data":[
                    {
                        "id": "be6204693d2da20b706cfec1592f9afc",
                        "name": "Weforms"
                    },

                    {
                        "id": "be6204693d2da20b706cfec1592f9afd",
                        "name": "WPUF"
                    }
                ]
            }


### Update A CampaignMonitor Contact [POST]
This API lets you update your contacts from the list


+ Response 201 (application/json)
    + Body
    
            {
                "success":true,
                "data":[
                    {
                        "id": "be6204693d2da20b706cfec1592f9afc",
                        "name": "Weforms"
                    },

                    {
                        "id": "be6204693d2da20b706cfec1592f9afd",
                        "name": "WPUF"
                    }
                ]
            }