# Group Getresponse


## Getresponse List [/getresponse/]

### Getresponse Contact List[GET]
This API endpoint helps you check all your subscribed contacts from Getresponse list


Fetches Getresponse

+ Response 200 (application/json)
    + Body
    
            {
                "success":true,
                "data":[
                    {
                        "id": "WSACP",
                        "name": "q7mkroksolars"
                    }
                ]
            }


### Update A Getresponse Contact  [POST]
With this piece of API, you can edit and update your Getresponse contacts

+ Response 201 (application/json)
    + Body
    
            {
                "success":true,
                "data":[
                    {
                        "id": "WSACP",
                        "name": "q7mkroksolars"
                    }
                ]
            }