# Group Googlesheets


## Googlesheets List [/googlesheets/sheets/]

### Checking Googlesheets List [GET]
This API endpoint helps you check all your customerss from Googlesheets list

Fetches Googlesheets Sheets

+ Response 200 (application/json)
    + Body
    
            {

            }

## Googlesheets List [/googlesheets/lists/]

### Update Googlesheets Customer List[GET]
Using this piece of API, you can edit and update your GoogleSheet customers' list

Fetches Googlesheets List

+ Response 200 (application/json)
    + Body
    
            {
                "success":true,
                "data":[
                    {
                        "id": "1b9dXArJcNJlIOQBKOLxebnohgXz5QkqcamB4hwBMLXE",
                        "name": "Weforms spreadsheet"
                    },

                    {
                        "id": "1PLmWMlqV4250u9S-zErYqIIIXV_hyXTaU2X3ljo-zcI",
                        "name": "weCricket(Responses)"
                    }
                ]
            }