# Group PDF


## PDF Download [/pdf/{entry_id}/download_entries/]

### PDF Download List[GET]
This piece of API helps you check your downloaded PDF list

Fetches PDF

+ Parameters
    + entry_id (number,required) -

+ Response 200 (application/json)
    + Body
    
            {

            }