# Group Salesforce


## Salesforce List [/salesforce/]

### Salesforce Contact List[GET]
This API allows you to check your contact list from Salesforce Contacts

Fetches Salesforce

+ Response 200 (application/json)
    + Body
    
            {

            }


### Update A Salesforce Contact [POST]
And using this API you can easily  edit and update your Salesforce contact list

+ Request (application/json)
    + Body
    
            {

            }

+ Response 201 (application/json)
    + Body
    
            {

            }