# Group Logs

## Logs [/logs/]

### Check Saved Logs [GET]

With this API endpoint, you can check your saved logs. If something wrong occurs, you would find them in your list of logs.

+ Response 200 (application/json)
    + Body
    
            {
                {
                    "message": ")"
                },
                {
                    "message": "    [entry_id] => 244"
                },
                {
                    "message": "    [form_id] => 1457"
                },
                {
                    "message": "        )"
                },
                {
                    "message": "            [weforms-front-quiz] => no"
                },
                {
                    "message": "            [weforms-front-report] => no"
                },
                {
                    "message": "            [action] => weforms_frontend_submit"
                },
                {
                    "message": "            [page_id] => 1460"
                },
                {
                    "message": "            [form_id] => 1457"
                },
                {
                    "message": "            [_wp_http_referer] => /wp-testing/entries-page/"
                },
                {
                    "message": "            [_wpnonce] => 6dbeb541a8"
                },
                {
                    "message": "            [text] => abcde"
                },
                {
                    "message": "                )"
                },
                {
                    "message": "                    [last] => islam"
                },
                {
                    "message": "                    [middle] => "
                },
                {
                    "message": "                    [first] => abcd"
                },
                {
                    "message": "                ("
                },
                {
                    "message": "            [name] => Array"
                },
                {
                    "message": "        ("
                },
                {
                    "message": "    [data] => Array"
                },
                {
                    "message": "    [message] => Thanks for contacting us! We will get in touch with you shortly."
                },
                {
                    "message": "    [show_message] => 1"
                },
                {
                    "message": "    [redirect_to] => "
                },
                {
                    "message": "    [success] => 1"
                },
                {
                    "message": "("
                },
                {
                    "0": "[29.08.2019 05:22:29][payment_response] Array",
                    "time": "3 hours ago",
                    "1": "29.08.2019 05:22:29",
                    "type": "payment_response",
                    "2": "payment_response",
                    "message": " Array",
                    "3": " Array"
                },
                {
                    "message": ")"
                },
                {
                    "message": "    [entry_id] => 243"
                },
                {
                    "message": "    [form_id] => 1457"
                },
                {
                    "message": "        )"
                },
                {
                    "message": "            [weforms-front-quiz] => no"
                },
                {
                    "message": "            [weforms-front-report] => no"
                },
                {
                    "message": "            [action] => weforms_frontend_submit"
                },
                {
                    "message": "            [page_id] => 1460"
                },
                {
                    "message": "            [form_id] => 1457"
                },
                {
                    "message": "            [_wp_http_referer] => /wp-testing/entries-page/"
                },
                {
                    "message": "            [_wpnonce] => 6dbeb541a8"
                },
                {
                    "message": "            [text] => abcd"
                },
                {
                    "message": "                )"
                },
                {
                    "message": "                    [last] => islam"
                },
                {
                    "message": "                    [middle] => "
                },
                {
                    "message": "                    [first] => momin"
                },
                {
                    "message": "                ("
                },
                {
                    "message": "            [name] => Array"
                },
                {
                    "message": "        ("
                },
                {
                    "message": "    [data] => Array"
                },
                {
                    "message": "    [message] => Thanks for contacting us! We will get in touch with you shortly."
                },
                {
                    "message": "    [show_message] => 1"
                },
                {
                    "message": "    [redirect_to] => "
                },
                {
                    "message": "    [success] => 1"
                },
                {
                    "message": "("
                },
                {
                    "0": "[29.08.2019 05:22:08][payment_response] Array",
                    "time": "3 hours ago",
                    "1": "29.08.2019 05:22:08",
                    "type": "payment_response",
                    "2": "payment_response",
                    "message": " Array",
                    "3": " Array"
                },
                {
                    "message": ")"
                },
                {
                    "message": "    [entry_id] => 242"
                },
                {
                    "message": "    [form_id] => 1457"
                },
                {
                    "message": "        )"
                },
                {
                    "message": "            [weforms-front-quiz] => no"
                },
                {
                    "message": "            [weforms-front-report] => no"
                },
                {
                    "message": "            [action] => weforms_frontend_submit"
                },
                {
                    "message": "            [page_id] => 1460"
                },
                {
                    "message": "            [form_id] => 1457"
                },
                {
                    "message": "            [_wp_http_referer] => /wp-testing/entries-page/"
                },
                {
                    "message": "            [_wpnonce] => 6dbeb541a8"
                },
                {
                    "message": "            [text] => abc"
                },
                {
                    "message": "                )"
                },
                {
                    "message": "                    [last] => islam"
                },
                {
                    "message": "                    [middle] => "
                },
                {
                    "message": "                    [first] => rokib"
                },
                {
                    "message": "                ("
                },
                {
                    "message": "            [name] => Array"
                },
                {
                    "message": "        ("
                },
                {
                    "message": "    [data] => Array"
                },
                {
                    "message": "    [message] => Thanks for contacting us! We will get in touch with you shortly."
                },
                {
                    "message": "    [show_message] => 1"
                },
                {
                    "message": "    [redirect_to] => "
                },
                {
                    "message": "    [success] => 1"
                },
                {
                    "message": "("
                },
                {
                    "0": "[29.08.2019 05:21:45][payment_response] Array",
                    "time": "3 hours ago",
                    "1": "29.08.2019 05:21:45",
                    "type": "payment_response",
                    "2": "payment_response",
                    "message": " Array",
                    "3": " Array"
                },
                {
                    "message": ")"
                },
                {
                    "message": "    [payment_method] => stripe"
                },
                {
                    "message": "    [stripe_message] => Please wait while the payment popup is loading."
                },
                {
                    "message": "        )"
                },
                {
                    "message": "            [currency] => USD"
                },
                {
                    "message": "            [amount] => 1000"
                },
                {
                    "message": "            [key] => pk_test_TgoXwICWUw5nLdozHcUFAlCB"
                },
                {
                    "message": "            [description] => Just another WordPress site"
                },
                {
                    "message": "            [name] => we"
                },
                {
                    "message": "            [image] => https://stripe.com/img/documentation/checkout/marketplace.png"
                },
                {
                    "message": "        ("
                },
                {
                    "message": "    [config] => Array"
                },
                {
                    "message": "    [entry_id] => 241"
                },
                {
                    "message": "    [form_id] => 1328"
                },
                {
                    "message": "        )"
                },
                {
                    "message": "            [weforms-front-quiz] => no"
                },
                {
                    "message": "            [weforms-front-report] => no"
                },
                {
                    "message": "            [action] => weforms_frontend_submit"
                },
                {
                    "message": "            [page_id] => 1455"
                },
                {
                    "message": "            [form_id] => 1328"
                },
                {
                    "message": "            [_wp_http_referer] => /wp-testing/transaction-page/"
                },
                {
                    "message": "            [_wpnonce] => 6dbeb541a8"
                },
                {
                    "message": "                )"
                },
                {
                    "message": "                    [quantity] => 1"
                },
                {
                    "message": "                    [price] => 10"
                },
                {
                    "message": "                    [name] => Single Product"
                },
                {
                    "message": "                ("
                },
                {
                    "message": "            [single_product] => Array"
                },
                {
                    "message": "            [payment_method] => stripe"
                },
                {
                    "message": "        ("
                },
                {
                    "message": "    [data] => Array"
                },
                {
                    "message": "    [message] => Thanks for contacting us! We will get in touch with you shortly."
                },
                {
                    "message": "    [show_message] => 1"
                },
                {
                    "message": "    [redirect_to] => "
                },
                {
                    "message": "    [success] => 1"
                },
                {
                    "message": "("
                },
                {
                    "0": "[29.08.2019 04:24:12][payment_response] Array",
                    "time": "4 hours ago",
                    "1": "29.08.2019 04:24:12",
                    "type": "payment_response",
                    "2": "payment_response",
                    "message": " Array",
                    "3": " Array"
                },
                {
                    "message": ")"
                },
                {
                    "message": "    [payment_method] => stripe"
                },
                {
                    "message": "    [stripe_message] => Please wait while the payment popup is loading."
                },
                {
                    "message": "        )"
                },
                {
                    "message": "            [currency] => USD"
                },
                {
                    "message": "            [amount] => 1000"
                },
                {
                    "message": "            [key] => pk_test_TgoXwICWUw5nLdozHcUFAlCB"
                },
                {
                    "message": "            [description] => Just another WordPress site"
                },
                {
                    "message": "            [name] => we"
                },
                {
                    "message": "            [image] => https://stripe.com/img/documentation/checkout/marketplace.png"
                },
                {
                    "message": "        ("
                },
                {
                    "message": "    [config] => Array"
                },
                {
                    "message": "    [entry_id] => 240"
                },
                {
                    "message": "    [form_id] => 1328"
                },
                {
                    "message": "        )"
                },
                {
                    "message": "            [weforms-front-quiz] => no"
                },
                {
                    "message": "            [weforms-front-report] => no"
                },
                {
                    "message": "            [action] => weforms_frontend_submit"
                },
                {
                    "message": "            [page_id] => 1455"
                },
                {
                    "message": "            [form_id] => 1328"
                },
                {
                    "message": "            [_wp_http_referer] => /wp-testing/transaction-page/"
                },
                {
                    "message": "            [_wpnonce] => 6dbeb541a8"
                },
                {
                    "message": "                )"
                },
                {
                    "message": "                    [quantity] => 1"
                },
                {
                    "message": "                    [price] => 10"
                },
                {
                    "message": "                    [name] => Single Product"
                },
                {
                    "message": "                ("
                },
                {
                    "message": "            [single_product] => Array"
                },
                {
                    "message": "            [payment_method] => stripe"
                },
                {
                    "message": "        ("
                },
                {
                    "message": "    [data] => Array"
                },
                {
                    "message": "    [message] => Thanks for contacting us! We will get in touch with you shortly."
                },
                {
                    "message": "    [show_message] => 1"
                },
                {
                    "message": "    [redirect_to] => "
                },
                {
                    "message": "    [success] => 1"
                },
                {
                    "message": "("
                },
                {
                    "0": "[29.08.2019 04:23:14][payment_response] Array",
                    "time": "4 hours ago",
                    "1": "29.08.2019 04:23:14",
                    "type": "payment_response",
                    "2": "payment_response",
                    "message": " Array",
                    "3": " Array"
                },
                {
                    "message": ")"
                },
                {
                    "message": "    [payment_method] => stripe"
                },
                {
                    "message": "    [stripe_message] => Please wait while the payment popup is loading."
                },
                {
                    "message": "        )"
                },
                {
                    "message": "            [currency] => USD"
                },
                {
                    "message": "            [amount] => 1000"
                },
                {
                    "message": "            [key] => "
                },
                {
                    "message": "            [description] => Just another WordPress site"
                },
                {
                    "message": "            [name] => we"
                },
                {
                    "message": "            [image] => https://stripe.com/img/documentation/checkout/marketplace.png"
                },
                {
                    "message": "        ("
                },
                {
                    "message": "    [config] => Array"
                },
                {
                    "message": "    [entry_id] => 239"
                },
                {
                    "message": "    [form_id] => 1328"
                },
                {
                    "message": "        )"
                },
                {
                    "message": "            [weforms-front-quiz] => no"
                },
                {
                    "message": "            [weforms-front-report] => no"
                },
                {
                    "message": "            [action] => weforms_frontend_submit"
                },
                {
                    "message": "            [page_id] => 1455"
                },
                {
                    "message": "            [form_id] => 1328"
                },
                {
                    "message": "            [_wp_http_referer] => /wp-testing/transaction-page/"
                },
                {
                    "message": "            [_wpnonce] => 6dbeb541a8"
                },
                {
                    "message": "                )"
                },
                {
                    "message": "                    [quantity] => 1"
                },
                {
                    "message": "                    [price] => 10"
                },
                {
                    "message": "                    [name] => Single Product"
                },
                {
                    "message": "                ("
                },
                {
                    "message": "            [single_product] => Array"
                },
                {
                    "message": "            [payment_method] => stripe"
                },
                {
                    "message": "        ("
                },
                {
                    "message": "    [data] => Array"
                },
                {
                    "message": "    [message] => Thanks for contacting us! We will get in touch with you shortly."
                },
                {
                    "message": "    [show_message] => 1"
                },
                {
                    "message": "    [redirect_to] => "
                },
                {
                    "message": "    [success] => 1"
                },
                {
                    "message": "("
                },
                {
                    "0": "[29.08.2019 04:22:24][payment_response] Array",
                    "time": "4 hours ago",
                    "1": "29.08.2019 04:22:24",
                    "type": "payment_response",
                    "2": "payment_response",
                    "message": " Array",
                    "3": " Array"
                }
            }

### Delete Logs [DELETE]
This API enables you delete certain types of logs or all at once

+ Request (application/json)
+ Response 200 (application/json)
    + Body
    
            {
                "message": "log file deleted"
            }